// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvMBPRuIbJVianzAjo1rRKyFY8RfNaF_g',
    appId: '1:150055874798:web:2333f51bf7c785b81203ff',
    messagingSenderId: '150055874798',
    projectId: 'opportunet-bd7b8',
    authDomain: 'opportunet-bd7b8.firebaseapp.com',
    storageBucket: 'opportunet-bd7b8.firebasestorage.app',
    measurementId: 'G-BSRGQTF2WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj6QYQN5lPTeJFBIBGa060sl9PcoewP2w',
    appId: '1:150055874798:android:c4e82796185ca2e11203ff',
    messagingSenderId: '150055874798',
    projectId: 'opportunet-bd7b8',
    storageBucket: 'opportunet-bd7b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs81aVHlzMAciYLWH8_auxfp6T0vx47rs',
    appId: '1:150055874798:ios:45ad0d35849855cb1203ff',
    messagingSenderId: '150055874798',
    projectId: 'opportunet-bd7b8',
    storageBucket: 'opportunet-bd7b8.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

}